### ISSUE TITLE
CUDA_NVCC_FLAGS variable not honored by CMakeLists.txt

### ISSUE THREAD

**Issue by luszczek** [icl-utk-edu/heffte#2]
After configuring heFFTe, the option `CUDA_NVCC_FLAGS` is listed as output but is not passed to the `nvcc` compiler.

For example, `cmake` invocation: `cmake -B /path/to/build -D Heffte_ENABLE_CUDA=On -D CUDA_NVCC_FLAGS=--no-such-flag /path/to/heffte/source/code ; cd /path/to/build ; make` finishes successfully even though `CUDA_NVCC_FLAGS` is set to invalid value.

The only way to pass flags to CUDA's compiler I could use was through the CMake's standard `CMAKE_CUDA_FLAGS` variable.

**Comment by mkstoyanov** [comment]
That was a leftover from when we transition to CUDA as a CMake language. Fixing now.

Thanks for reporting!
